LBS_DEPTS = [
    {"name": "Property Management & Customer Relations", "m": 36, "f": 27},
    {"name": "Accounts & Finance", "m": 13, "f": 43},
    {"name": "Sales & Marketing", "m": 18, "f": 33},
    {"name": "Credit Administration", "m": 10, "f": 37},
    {"name": "Project - Klang Valley", "m": 33, "f": 13},
    {"name": "Scapes Hotel", "m": 16, "f": 25},
    {"name": "M3 Mall", "m": 15, "f": 14},
    {"name": "Group Performance Excellence", "m": 9, "f": 6},
    {"name": "Driver", "m": 12, "f": 0},
    {"name": "Project & Office - Cameron Highlands", "m": 6, "f": 6},
    {"name": "Contract", "m": 2, "f": 9},
    {"name": "Human Resources", "m": 3, "f": 8},
    {"name": "Corporate Integrity & Sustainability", "m": 0, "f": 9},
    {"name": "Treasury", "m": 4, "f": 5},
    {"name": "Admin", "m": 3, "f": 5},
    {"name": "Project & Office - Batu Pahat", "m": 4, "f": 4},
    {"name": "Board of Directors", "m": 5, "f": 1},
    {"name": "Corporate Communication", "m": 4, "f": 2},
    {"name": "Legal", "m": 5, "f": 1},
    {"name": "Special Project Office", "m": 3, "f": 3},
    {"name": "Personal Assistant / Secretary", "m": 1, "f": 4},
    {"name": "Project & Office - Ipoh", "m": 2, "f": 3},
    {"name": "Business Development", "m": 3, "f": 1},
    {"name": "Com Secretarial & Corp Affair", "m": 0, "f": 4},
    {"name": "Executive Chairman Office", "m": 1, "f": 3},
    {"name": "Leaptec", "m": 1, "f": 1},
]

MGB_DEPTS = [
    {"name": "Construction", "m": 88, "f": 15},
    {"name": "MGB Sany Nilai Manufacturing", "m": 28, "f": 5},
    {"name": "HR, Operation & Admin", "m": 15, "f": 10},
    {"name": "QAQC", "m": 11, "f": 12},
    {"name": "Accounts", "m": 6, "f": 10},
    {"name": "Account Payable", "m": 3, "f": 11},
    {"name": "Contract", "m": 6, "f": 8},
    {"name": "Procurement", "m": 0, "f": 13},
    {"name": "Construction Support", "m": 6, "f": 5},
    {"name": "MGB Sany HQ Management", "m": 4, "f": 7},
    {"name": "Plant & Machinery", "m": 10, "f": 1},
    {"name": "Project", "m": 9, "f": 2},
    {"name": "Credit Admin", "m": 0, "f": 10},
    {"name": "Customer Service", "m": 4, "f": 5},
    {"name": "Land & Development 1", "m": 1, "f": 8},
    {"name": "Planner & Construction Analytics", "m": 2, "f": 7},
    {"name": "MGBI HQ Management", "m": 2, "f": 6},
    {"name": "Technical", "m": 6, "f": 2},
    {"name": "Land & Development 2", "m": 6, "f": 1},
    {"name": "Sales & Marketing", "m": 0, "f": 7},
    {"name": "Project Management", "m": 1, "f": 5},
    {"name": "VadTech & IT", "m": 6, "f": 0},
    {"name": "Personal Assistant / Secretary", "m": 2, "f": 3},
    {"name": "Tender", "m": 1, "f": 4},
    {"name": "Treasury & Investor Relations", "m": 0, "f": 5},
    {"name": "Property Management", "m": 0, "f": 3},
    {"name": "Secretarial & Corporate Affairs", "m": 0, "f": 3},
    {"name": "Corporate Communication, Media & Digital", "m": 2, "f": 0},
    {"name": "Corporate Control", "m": 0, "f": 2},
    {"name": "HSE", "m": 2, "f": 0},
    {"name": "Industry Development", "m": 1, "f": 1},
    {"name": "Risk & Sustainability", "m": 2, "f": 0},
    {"name": "Internal Audit", "m": 0, "f": 1},
    {"name": "Legal", "m": 0, "f": 1},
    {"name": "Strategic Partnership", "m": 0, "f": 1},
]


def all_dept_names():
    return sorted(set([d["name"] + " (LBS)" for d in LBS_DEPTS] + [d["name"] + " (MGB)" for d in MGB_DEPTS]))
